version: "1.0"
info:
  model: int-scaffold
packages:
- name: EdgeTechCommunityDemo
  gitServerName: JohnBoy
  gitUrl: https://github.com/johnpcarter/EdgeTechCommunityDemo
  gitUsername: johnpcarter
  gitToken: edge.scaffolding.EdgeTechCommunityDemo.JohnBoy.gitToken
  gitBranch: main
- name: JcPublicTools
  gitServerName: JohnBoy
  gitUrl: https://github.com/johnpcarter
  gitUsername: johnpcarter
  gitToken: edge.scaffolding.JcPublicTools.JohnBoy.gitToken
  gitTag: v2.1.0
