version: "1.0"
info:
  model: int-scaffold
services:
- serviceName: edge.techcommunitydemo.integrations:helloWorld
  packages:
  - name: EdgeTechCommunityDemo
    version: "1.0"
  - name: JcPublicTools
    version: "5.0"
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.0.0.0.560
- serviceName: jc.tools.pub.list:containsString
  packages:
  - name: JcPublicTools
    version: "5.0"
packages:
- name: EdgeTechCommunityDemo
  gitServerName: JohnBoy
  gitUrl: https://github.com/johnpcarter/EdgeTechCommunityDemo
  gitUsername: johnpcarter
  gitToken: edge.scaffolding.EdgeTechCommunityDemo.JohnBoy.gitToken
  gitBranch: main
- name: JcPublicTools
  gitServerName: JohnBoy
  gitUrl: https://github.com/johnpcarter
  gitUsername: johnpcarter
  gitToken: edge.scaffolding.JcPublicTools.JohnBoy.gitToken
  gitTag: v2.1.0
