version: "1.0"
info:
  model: int-scaffold
services:
- serviceName: edge.techcommunitydemo.integrations:helloWorld
  packages:
  - name: EdgeTechCommunityDemo
    version: "1.0"
  - name: JcPublicTools
    version: "5.0"
  - name: OnPremiseISPkg
    version: "1.0"
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.0.0.0.560
- serviceName: jc.tools.pub.list:containsString
  packages:
  - name: JcPublicTools
    version: "5.0"
- serviceName: OnPremiseISPkg.REST.openweather_.services:CurrentWeatherData
  packages:
  - name: OnPremiseISPkg
    version: "1.0"
- serviceName: pub.client:http
  packages:
  - name: WmPublic
    version: 11.0.0.0.560
- serviceName: pub.json:jsonStreamToDocument
  packages:
  - name: WmPublic
    version: 11.0.0.0.560
- serviceName: pub.json:documentToJSONString
  packages:
  - name: WmPublic
    version: 11.0.0.0.560
packages:
- name: EdgeTechCommunityDemo
  gitServerName: JohnBoy
  gitUrl: https://github.com/johnpcarter/EdgeTechCommunityDemo
  gitUsername: johnpcarter
  gitToken: edge.scaffolding.EdgeTechCommunityDemo.JohnBoy.gitToken
  gitBranch: main
- name: OpenWeatherClient
  gitServerName: RAHS_SAG_GitHub
  gitUrl: https://github.softwareag.com/rahs
  gitUsername: rahs
  gitToken: edge.scaffolding.OpenWeatherClient.RAHS_SAG_GitHub.gitToken
  gitBranch: main
